- name: rsync some files
  synchronize:
    src: "{{ src_lua_dir }}/{{ server}}/"
    dest: "{{remote_lua_dir }}/{{ server }}"
    mode: push
    delete: yes
    compress: yes
    group: yes
    owner: yes
    rsync_opts:
      - "--exclude=mod.txt"
      - "--exclude=proto"
      - "--exclude=config_gatesvrd"
      - "--exclude=config_cfgcenter"
      - "--exclude=config_tcpsvrd"
      - "--exclude=config_datadbsvrd"
      - "--exclude=logs"
      - "--exclude=server.sh"
      - "--exclude=config"
      #- "--rsh=ssh {{ ansible_ssh_common_args }}"
    use_ssh_args: yes
  ignore_errors: yes
  register: result
  tags:
    - updatelua

- name: rsync some files
  template:
    src: "/var/lib/jenkins/workspace/lua-game-chess/lua-game-conf/{{ server_node }}/config/svr/config_clusters.j2"
    dest: "{{ remote_lua_conf }}/config_clusters"
    group: code
    owner: code
    mode: 0755
  tags:
    - updatelua

- name: rsync some files
  template:
    src: "/var/lib/jenkins/workspace/lua-game-chess/lua-game-conf/{{ server_node }}/config/svr/config_svrs.j2"
    dest: "{{ remote_lua_conf }}/config_svrs"
    group: code
    owner: code
    mode: 0755
  tags:
    - updatelua

- name: modify some permission
  file:
    dest: "/home/code/"
    owner: code
    group: code
    mode: 0755
    recurse: yes
  tags:
    - updatelua

- name: update some server
  become: yes
  become_method: su
  become_user: code
  shell: "cd /home/code/trunk/gameserver/ && ./server.sh {{ method }} {{ server }}"
  register: check
  tags:
    - updatelua

- name: show result
  debug:
    msg: "{{check}}"
  tags:
    - updatelua
