- name: rsync lua code
  synchronize:
    src: "{{ src_lua_dir }}/{{ server}}/"
    dest: "{{remote_lua_dir }}/{{ server }}"
    mode: push
    delete: yes
    compress: yes
    group: yes
    owner: yes
    rsync_opts:
      - "--exclude=mod.txt"
      - "--exclude=proto"
      - "--exclude=config_gatesvrd"
      - "--exclude=config_cfgcenter"
      - "--exclude=config_tcpsvrd"
      - "--exclude=config_datadbsvrd"
      - "--exclude=logs"
      - "--exclude=server.sh"
      - "--exclude=config"
      #- "--rsh=ssh {{ ansible_ssh_common_args }}"
    use_ssh_args: yes
  ignore_errors: yes
  register: result
  tags:
    - rsyncluacode

- name: rsync lua conf config_clusters
  template:
    src: "/var/lib/jenkins/workspace/lua-game-chess/lua-game-conf/{{ server_node }}/config/svr/config_clusters.j2"
    dest: "{{ remote_lua_conf }}/config_clusters"
    group: code
    owner: code
    mode: 0755
  tags:
    - rsyncluaconfig

- name: rsync lua conf config_svrs
  template:
    src: "/var/lib/jenkins/workspace/lua-game-chess/lua-game-conf/{{ server_node }}/config/svr/config_svrs.j2"
    dest: "{{ remote_lua_conf }}/config_svrs"
    group: code
    owner: code
    mode: 0755
  tags:
    - rsyncluaconfig

- name: rsync config_dbhash
  synchronize:
    src: "/var/lib/jenkins/workspace/lua-game-chess/lua-game-conf/{{ server_node }}/config/svr/config_dbhash"
    dest: "{{ remote_lua_conf }}/config_dbhash"
    mode: push
    delete: yes
    compress: yes
    use_ssh_args: yes
  tags:
    - rsyncluaconfig


- name: rsync lua business
  synchronize:
    src: "/var/lib/jenkins/workspace/lua-game-chess/lua-game-conf/{{ server_node }}/config/business/"
    dest: "/home/code/trunk/gameserver/config/business"
    mode: push
    compress: yes
    delete: yes
  tags:
    - rsyncconfig

- name: rsync json config
  synchronize:
    src: "/var/lib/jenkins/workspace/lua-game-chess/lua-game-conf/{{ server_node }}/config/json/"
    dest: "/home/code/trunk/gameserver/config/json"
    mode: push
    compress: yes
    delete: yes
  tags:
    - rsyncjsonconfig

- name: rsync lua common
  synchronize:
    src: "{{ src_lua_common }}"
    dest: "{{ remote_lua_common }}"
    mode: push
    delete: yes
    compress: yes
    group: yes
    owner: yes
    rsync_opts:
      - "--exclude=3rd"
      - "--exclude=object"
      - "--exclude=skynet"
      - "--exclude=tools"
      - "--exclude=README.md"
      #- "--rsh=ssh {{ ansible_ssh_common_args }}"
    use_ssh_args: yes
  tags:
    - rsyncluacommon

- name: rsync lua pay
  synchronize:
    src: "{{ src_lua_pay }}"
    dest: "{{ remote_lua_pay }}"
    mode: push
    delete: yes
    compress: yes
    group: yes
    owner: yes
    #rsync_opts: [ "--rsh=ssh {{ ansible_ssh_common_args }}" ]
    use_ssh_args: yes
  tags:
    - rsyncluapay

- name: modify gameserver permission
  file:
    dest: "/home/code/"
    owner: code
    group: code
    mode: 0755
    recurse: yes
  tags:
    - modifypermit

- name: update server
  become: yes
  become_method: su
  become_user: code
  environment:
      PATH: /home/code/bin/lbf:/root/bin/lbf:/root/bin/lbf:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin
  shell: "cd /home/code/trunk/gameserver/ && ./server.sh {{ method }} {{ server }}"
  register: check
  tags:
    - updatelua

- name: show
  debug:
    msg: "{{check}}"
  tags:
    - updatelua
