- name: Import Vars
  include_vars: "{{ item }}"
  with_items:
   - "main.yml"

- name: install zabbix-agent 
  yum: name={{ Zabbix_Agent_Package }}

- name: install configutation file for zabbix-agent
  template: src=zabbix_agentd.conf.j2 dest=/etc/zabbix/zabbix_agentd.conf
  tags:
  - conf
  notify:
  - restart zabbix-agentd

- name: copy file
  synchronize: src=/etc/ansible/files/ dest=/etc/zabbix/zabbix_agentd.d/
  tags:
  - confsh
  notify:
  - restart zabbix-agentd

- name: start zabbix_agentd service
  service: enabled=true name=zabbix-agent state=started
